### ISSUE TITLE
EAF pdf can not work well with pymupdf 1.14

### ISSUE THREAD

**Issue by tumashu** [manateelazycat/emacs-application-framework#414]
```
Traceback (most recent call last):
  File "/home/feng/projects/emacs-packages/emacs-application-framework/app/pdf-viewer/buffer.py", line 504, in paintEvent
    qpixmap = self.get_page_pixmap(index, self.scale, self.rotation)
  File "/home/feng/projects/emacs-packages/emacs-application-framework/app/pdf-viewer/buffer.py", line 389, in get_page_pixmap
    imagelist = page.getImageList(full=True)
TypeError: getImageList() got an unexpected keyword argument 'full'

```

**Comment by tumashu** [comment]
Debian stable's mupdf is 1.14,  can not install pymupdf > 1.14 easily.

**Comment by manateelazycat** [comment]
你先把 full=True 删除了，测试下看看是否正常工作？

如果可以的话，我会写一个兼容性补丁。

**Comment by tumashu** [comment]
我试过，最起码可以打开文件了

**Comment by tumashu** [comment]
其他不常用的命令我没试过

**Comment by manateelazycat** [comment]
> 我试过，最起码可以打开文件了

建议多测试下，我晚上打补丁

**Comment by tumashu** [comment]
试了一遍pdf浏览器的命令，没发现其它问题

**Comment by manateelazycat** [comment]
最新版增加了兼容性，更新即可。
